apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun5
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: picalc-git
  params:
    - name: pathToYamlFile
      value: "./picalc.yaml"
    - name: imageUrl
      value: harbor.ops.action.cloudz.co.kr/intern_test/picalc
    - name: imageTag
      value: "1.0"
  trigger:
    type: manual
  serviceAccount: pipeline-account
